---
language: ruby

bundler_args: "--without system_tests development"

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake validate lint spec strings:generate reference'

matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.1
    sudo: required
    services: docker
    env: BEAKER_set="centos-6" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.4.4
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet5
    bundler_args:
    script: bundle exec rake beaker
  - rvm: 2.5.1
    sudo: required
    services: docker
    env: BEAKER_set="centos-7" BEAKER_PUPPET_COLLECTION=puppet6
    bundler_args:
    script: bundle exec rake beaker

notifications:
  email: false

deploy:
  provider: puppetforge
  user: ghoneycutt
  password:
    secure: "nj8F6mM86w+6XOCUrFZpsyC0wnVvK9u4a2YimYN7B73pF0/8RcH+9KTwrklxDgLZsu1VmxmrDBhHJr01K85qPYy1eKbebwSDGIxwtDmZmTbdWgcFqsQ8BGdVP2+e1A8I7y9MRkdmXdTsmfRojwgplLL2xp+bYg3PUtm702VYxC4="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
