---
language: ruby

bundler_args: "--without system_tests development"

cache: bundler

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

sudo: false

script: SPEC_OPTS="--format documentation" bundle exec rake $CHECK

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4" CHECK=test
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5" CHECK=test
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 5" CHECK=release DEPLOY_TO_FORGE=yes
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6" CHECK=test

notifications:
  email: false

deploy:
  provider: puppetforge
  user: ghoneycutt
  passwd:
    secure: lcCrxzkD6hrfv/ENMHyvVeCe70qn0hYxYsKeiUppnCGwxoZVRBcuhok8qrudqNKlIu0n5tYpeq+o56iDuL/NvjxumUw7AGMCAKBvo0F2XoAo+wMuQCkGqjHeEvRJJIX5rbvVHvffA8CjxHuyCNmb0rqmhzPr/VFMSXJ5kYvhIFs=
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
