name    'ghoneycutt-selinux'
version '1.1.0'
source 'git://github.com/ghoneycutt/puppet-module-selinux.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage SELinux'
description 'manage selinux'
project_page 'https://github.com/ghoneycutt/puppet-module-selinux'

dependency 'puppetlabs/stdlib',  '>= 3.2.0'
